# Generated by Django 6.0.5 on 2026-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_ra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ra', models.CharField(max_length=100, unique=True)),
                ('descripcion_ra', models.TextField(blank=True)),
                ('origen_ra', models.CharField(blank=True, max_length=100)),
                ('tipo_produccion_ra', models.CharField(max_length=20)),
                ('activo_ra', models.BooleanField(default=True)),
                ('created_at_ra', models.DateTimeField(auto_now_add=True)),
                ('updated_at_ra', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'razas',
            },
        ),
    ]
