# Generated by Django 6.0.5 on 2026-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id_po', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_po', models.CharField(max_length=20, unique=True)),
                ('nombre_po', models.CharField(max_length=100)),
                ('hectareas_po', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacidad_maxima_po', models.IntegerField()),
                ('estado_po', models.CharField(default='disponible', max_length=20)),
                ('latitud_po', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_po', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('observaciones_po', models.TextField(blank=True)),
                ('created_at_po', models.DateTimeField(auto_now_add=True)),
                ('updated_at_po', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'potreros',
            },
        ),
    ]
