# Generated by Django 6.0.5 on 2026-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_dieta_insumoalimenticio_modeloml_productoveterinario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloml',
            name='metricas_extra_mm',
            field=models.JSONField(blank=True, null=True, verbose_name='Métricas Extendidas (ML)'),
        ),
    ]
