"""
Django settings for ganadoSWG project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url
import os
from pathlib import Path

# CLAUDINARY
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SEGURIDAD
# ==========================================
SECRET_KEY = 'django-insecure-^)r!fe^4tho3&ipvc$jupgg=pjj5%8+rhx2fysz7%q7p_lq#fx'

# ⚠️ IMPORTANTE: DEBUG debe ser False en producción
DEBUG = False

ALLOWED_HOSTS = ['ganadoswg.onrender.com', 'localhost', '127.0.0.1']

# ==========================================
# APLICACIONES
# ==========================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Aplicaciones.Gestion',
]

# ==========================================
# MIDDLEWARE (WhiteNoise correctamente ubicado)
# ==========================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← Justo aquí (después de Security)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ganadoSWG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ganadoSWG.wsgi.application'

# ==========================================
# BASE DE DATOS - CONEXIÓN HÍBRIDA
# ==========================================
# ⚠️ Toma DATABASE_URL desde las variables de entorno de Render
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # 🔥 PRODUCCIÓN: Usa la base de datos de Render
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # 💻 DESARROLLO LOCAL: Usa PostgreSQL en tu PC
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'bdd_RENDERlocal',
            'USER': 'postgres',
            'PASSWORD': 'root',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# ==========================================
# VALIDACIÓN DE CONTRASEÑAS
# ==========================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================
# INTERNACIONALIZACIÓN
# ==========================================
LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_TZ = True

# ==========================================
# ARCHIVOS ESTÁTICOS
# ==========================================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 🔥 WhiteNoise para archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==========================================
# ARCHIVOS MEDIA (Subidas de usuarios)
# ==========================================
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================
# CONFIGURACIÓN DE CORREO (GMAIL)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alpaaguirre1999@gmail.com'
EMAIL_HOST_PASSWORD = 'piry mxhv iqip kazv'
DEFAULT_FROM_EMAIL = 'Hacienda El Roble <alpaaguirre1999@gmail.com>'

# ==========================================
# CONFIGURACIÓN DE CLOUDINARY
# ==========================================
cloudinary.config(
    cloud_name='dnqf7nccg',
    api_key='324326838774969',
    api_secret='XRZMsNoEGLASui9KgyehZojyugw',
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'